spring.application.name=settlement-reconciliation

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/settlement_db
spring.datasource.username=app
spring.datasource.password=app
spring.jpa.hibernate.ddl-auto=validate

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.contexts=dev

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# S3 (LocalStack)
app.s3.endpoint=http://localhost:4566
app.s3.region=us-east-1
app.s3.bucket=settlement-files
